# Generated by Django 2.2.1 on 2019-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('year', models.CharField(max_length=4)),
                ('poster', models.TextField()),
                ('contentRating', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=20)),
                ('releaseDate', models.DateField()),
                ('averageRating', models.IntegerField()),
                ('originalTitle', models.CharField(max_length=90)),
                ('storyline', models.TextField()),
                ('imdbRating', models.FloatField()),
                ('posterurl', models.TextField()),
                ('actor', models.ManyToManyField(to='moviesApp.Actor')),
                ('genre', models.ManyToManyField(to='moviesApp.Genre')),
                ('rating', models.ManyToManyField(to='moviesApp.Rating')),
            ],
        ),
    ]
